### ISSUE TITLE
MetroGrid Crashes While Scrolling Using Mouse Wheel (ArgumentOutOfRangeException)

### ISSUE THREAD

**Issue by mobedi** [viperneo/winforms-modernui#297]
On many occasions when I use the MouseWheel to scroll up and down on my `MetroGrid` I get an `ArgumentOutOfRangeException`. Error message is 
> A first chance exception of type 'System.ArgumentOutOfRangeException'
> occurred in System.Windows.Forms.dll Additional information: Specified
> argument was out of the range of valid values.

**StackTrace:**

       at System.Windows.Forms.DataGridView.set_FirstDisplayedScrollingRowIndex(Int32 value)
       at MetroFramework.Controls.MetroDataGridHelper._scrollbar_Scroll(Object sender, ScrollEventArgs e)
       at MetroFramework.Controls.MetroScrollBar.OnScroll(ScrollEventType type, Int32 oldValue, Int32 newValue, ScrollOrientation orientation)
       at MetroFramework.Controls.MetroScrollBar.set_Value(Int32 value)
       at MetroFramework.Controls.MetroScrollBar.OnMouseWheel(MouseEventArgs e)
       at System.Windows.Forms.Control.WmMouseWheel(Message& m)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
       at Prospect.UserControlOverview.btnViewContacts_Click(Object sender, EventArgs e) in c:\Users\pedram.mobedi\Documents\Visual Studio 2013\Projects\Prospect\UserControlOverview.cs:line 39

It apparently has something to do with MetroGrid's value for `FirstDisplayedScrollingRowIndex`. I'm not quite sure how I can prevent this when I add `try-catch` on my MetroGrid's `OnScroll` and `OnMouseWheel` events the exception is still not caught. Is there a workaround for this? I am using a few of the grids on my program and I just love the way they look and don't want to go back to the boring old `DataGridView`.

I have set my MetroGrid to be `DoubleBuffered`. I hope that is not why this happens. Has anyone faced the same problem?

**SOLVED:**
Thanks to @DBenS suggestion. I was able to silent this Exception by adding the MetroFramework library in my solution. I am using the @fozzedout's version that does not crash at the beginning. It can be found here. https://github.com/fozzedout/winforms-modernui

I realize that the `ArgumentOutOfRangeException` is occurring in `MetroGrid.cs` method `_scrollbar_Scroll`. This is how I changed it:

    void _scrollbar_Scroll(object sender, System.Windows.Forms.ScrollEventArgs e)
    {
        if (_ignoreScrollbarChange > 0) return;
    
        if (_ishorizontal)
        {
            hScrollbar.Value = _scrollbar.Value;
    
            try
            {
                _grid.HorizontalScrollingOffset = _scrollbar.Value;
            }
            catch { }
        }
        else
        {
            try
            {
                if (_scrollbar.Value >= 0 && _scrollbar.Value < _grid.Rows.Count)
                    _grid.FirstDisplayedScrollingRowIndex = _scrollbar.Value + (_scrollbar.Value == 1 ? -1 : 1);
            }
            catch
            { }
                    
        }
    
        _grid.Invalidate();
    }

**Comment by DBenS** [comment]
Did you test it using the Demo project with the same results?
I made some tests here (grid full of data, just one row, no rows at all) and with no one situation the error raised.

**Comment by LeeDaiHung** [comment]
meet the same problem as you, how did you solve this problem?

**Comment by mobedi** [comment]
@LeeDaiHung No unfortunately the problem still resists. I will try to take a closer look otherwiose I would have to replace all my `MetroGrid`s with a normal `DataGridView`.

**Comment by mobedi** [comment]
@DBenS actually I am using the same `MetroGrid` that I was using in my other project and it works just fine there. That's why I have problems figuring out why it does not work on this one. Is it because I am using Entity Framework. That seems a bit unlikely because I am actually not binding the grid.

**Comment by mobedi** [comment]
As I am investigating a little more, when I scroll all the way down to the bottom of the `MetroGrid`, the vertical scroll bar does not scroll all the way down. This creates a gap area that you see in the picture:
![capture](https://cloud.githubusercontent.com/assets/2116627/8649350/c510fdee-2969-11e5-9bc8-86ddf6d1e256.PNG)
The program crashes exactly when I click on this empty area. So chances are when we click on this gap, `MetroGrid` is trying to set the `FirstDisplayedScrollingRowIndex` to something either negative or bigger than the actual number of items on the grid. These are just my conclusions for now. But is there a way to prevent the `MetroGrid` from setting this value?

**Comment by DBenS** [comment]
Hmmm....  I´m not using Metrogrid by binding a database. I´m just using it to achieve some data I put and update manually, even being a database (not using a Datasource and other automated binds).

I´m using the Entity Framework. My Framework is 4.0 full (not client).

**Comment by mobedi** [comment]
@DBenS This seems to be a hard one now. Meanwhile I will have to remove all my `MetrGrids` and replace them with normal `DataGridView`s which are quite ugly. Hope there will be a solution found soon.

**Comment by DBenS** [comment]
You may try to add the Metroframework as a source into you project, compile them in DEBUG mode and try to locate exactly in which line the error occurs.  

But something occurred in my mind seeing your image:  if the bar does not go to the end of interface, should be because the grid is reading some data that you´re not seeing. 

Just to try a solution: is it possible to the data in database has some "special characters" or even phantom chars/records that are causing the problem in grid? Think about the "next line" (and record) could have a special forgotten char (even an EOF char) that could be confusing the datagrid.

Seeing the errors above, did you tried also put (and take off) the name of OWNER during the Showdialog() that starts the grid?

**Comment by mobedi** [comment]
@DBenS Adding `MetroFramework` as source seems like a very good solution indeed. I am using the `.dll` files and it's very frustrating since with every small issue I have to recreate them. The reason I didn't do it was that the github code was not working. Hope the latest version is error-free so I can use that one instead.

I don't see any special characters in the grid. I have also checked the database.

The exception is caught in my `Program.cs` and in `Application.Run(new Main());` so I am not using the `ShowDialog()` in this case. My `MetroGrid` is on a user control that is located on my main form.

**Comment by DBenS** [comment]
If it can help you, try to do what I did before:

1- I download the last published version here.
2- I wend selecting ALL updates in source, selecting the VIEW SOURCE, copying all data and pasting into the correspondent code within MetroFramework.
3- So, I compiled the project again.

Another tip: in another thread I said we cannot update controls during the LOAD event because Metroframework seems to have sme conflicts between its REFRESH (the main form appears incorrectly when I try to set sme control properties within the LOAD event). I don´t program in C#, so, I don´t know if you´re doing that kind of operation here...

Are you firing the Grid.Update or Gird.Refresh after bnding in to your database?

Follows some things I do here (in VB.NET) trying to help you:

1- I force the DoubleBuffer in code (gridsetores is my grid):

gridSetores.GetType.InvokeMember("DoubleBuffered", _
                                Reflection.BindingFlags.NonPublic Or _
                                Reflection.BindingFlags.Instance Or _
                                System.Reflection.BindingFlags.SetProperty, _
                                Nothing, gridSetores, New Object() {True})


2- Force grid to select, always, an entire row:

 gridSetores.SelectionMode = DataGridViewSelectionMode.FullRowSelect
 gridSetores.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.Single
 gridSetores.Style = MetroFramework.MetroColorStyle.Silver


3- Manually add data into the grid:

 If gridSetores.Rows.Count = 0 Then
                For Each SetorNome As String In SetoresDaEmpresa
                    Dim linha As New DataGridViewRow
                    linha.CreateCells(gridSetores)
                    With linha
                        .Cells(1).Value = SetorNome
                    End With
                    GridSetoresCurrentLine = gridSetores.Rows.Add(linha)
                Next
            End If

Once the data is appended into the grid, all other events and functions are automated like yours. The ONLY thing is that the grid is not binding a table.

I have 6 different grid here, with different data and formats and Style (even using the DEFAULT with StyleManager). None of them are firing the same error.

My DLL´s are compiled in Net Framework 4 Full - see closed issue #293 to see what I made here to compile the code without RUNTIME errors.

Good luck!

**Comment by mobedi** [comment]
@DBenS thanks. I keep all the points you mentioned in mind.

**Comment by DBenS** [comment]
My pleasure. I hope you get success.

**Comment by mobedi** [comment]
@DBenS There are four  projects in the Guthub solution. Do I have to include all except "Demo"?

**Comment by mobedi** [comment]
@DBenS Damn! The code still throws the same exception as before. I thought they had already fixed this a long time ago.

**Comment by mobedi** [comment]
@DBenS the demo project cannot be run due to the `NullReferenceException` that occurs on `MetroForm.cs` on the line `windowButtonList.TryGetValue(WindowButtons.Maximize, out btn);` an old error.

**Comment by mobedi** [comment]
I am trying @fozzedout's version now. Here the above issue seems to be fixed and I see that it is throwing the same exception on the DataGrid but I can now see exactly where it happens. Will post the solution as soon as I fixed it myself. @fozzedout's fork is here: https://github.com/fozzedout/winforms-modernui

**Comment by mobedi** [comment]
@LeeDaiHung
I updated my post with my solution. Or may I say, silencing the exception. Please take a look!

**Comment by LeeDaiHung** [comment]
Thank you @mobedi 
I try to catch the exception at `Application.ThreadException` and `AppDomain.CurrentDomain.UnhandledException`, work for my program.
and used your solution, it's work too.

**Comment by LeeDaiHung** [comment]
@mobedi 
I have used your solution, still throw `ArgumentOutOfRangeException`.

I checked, the exception throws from `MetroGrid.cs: Line 180`, due the `this.FirstDisplayedScrollingRowIndex++` > `RowCount`, i changed the `else if` (line 178) as below,
``` csharp
else if (e.Delta < 0 && (this.FirstDisplayedScrollingRowIndex + 1 < this.RowCount))
```

Everything seems okay.

**Comment by DBenS** [comment]
Hmmm....  I really didn´t see the routine, but one thing called my attention: the critics are related to "more" and "less" zero. But If the value would be zero?

**Comment by DBenS** [comment]
Hmmmm...   I guess the problem is a little bit solved - at least, during my tests I could fire the problem all times and after my changes, the problem did not fired anymore. :+1: 

The problem is related to the ScrollBar, the amount of records on Grid and the size of Mainform...

We must consider that the SIZE O SCROLLBAR will vary according these parameters. Let´s imagine a Grid (ie: with 30 records) and a form with 400 pixels height. The scrollbar will appear with a certain size, ins´t it?  And, if we grow the form height, for instance, to 800 pixels? The scrollbar will grow in a proportional manner - at least, this must happen if the Scrollbar is 100%.

**In my tests I noted the problem is related to these 3 parameters (records, form size, scrollbar size)** and just because this, the problem is inconstant. And I found a solution (I hope):

```
MetroGrid.cs: Line 340
{
    if (_scrollbar.Value >= 0 && _scrollbar.Value <= _grid.Rows.Count)
        _grid.FirstDisplayedScrollingRowIndex = _scrollbar.Value + (_scrollbar.Value == 1 ? -1 : 1);
 }
```

Change to:

```
MetroGrid.cs: Line 340
{
    if (_scrollbar.Value >= 0 && _scrollbar.Value <= _grid.Rows.Count)
        _grid.FirstDisplayedScrollingRowIndex = _scrollbar.Value -1;
 }
```

@mobedi , @LeeDaiHung  could you please try to validate it in runtime?
In my case, it really solved the problem that *HAD NEVER* happened here UNTIL I try to estimulate the error.

Hugs!
